### Partie 1 - Rappel python
1- 

In [1]:
a = float(input("a: "))
b = float(input("b: "))
c = float(input("c: "))

In [2]:
import math
d = pow(b, 2) - 4 * a * c

In [3]:
if d > 0:
    root1 = (-b + math.sqrt(d)) / (2*a)
    root2 = (-b - math.sqrt(d)) / (2*a)
    print(f"The roots are: {root1} and {root2}")
    print(f"result 1= {a * pow(root1, 2) + b * root1 + c}")
    print(f"result 2= {a * pow(root2, 2) + b * root2 + c}")
elif d == 0:
    root = -b / (2*a)
    print(f"The root is: {root}")
    print(f"result 2= {a * pow(root, 2) + b * root + c}")
else:
    real_part = -b / (2*a)
    imaginary_part = math.sqrt(-d) / (2*a)
    root1 = complex(real_part, imaginary_part)
    root2 = complex(real_part, -imaginary_part)
    print(f"The roots are complex: {root1} and {root2}")
    print(f"result 1= {a * pow(root1, 2) + b * root1 + c}")
    print(f"result 2= {a * pow(root2, 2) + b * root2 + c}")

The roots are complex: (-0.3333333333333333+0.47140452079103173j) and (-0.3333333333333333-0.47140452079103173j)
result 1= 0j
result 2= 0j


2-

In [4]:
def nombreOcurrences(caractere, mot):
    count = 0
    for c in mot:
        if c == caractere:
            count += 1
    return count

In [5]:
nombreOcurrences('a', 'java')

2

### Partie 2 - La bibliothèque numpy
1-

In [6]:
revenus = [1800, 1500, 2200, 3000, 2172]

2-

In [7]:
def moy(revenus):
    sum = 0
    for i in range(len(revenus)):
        sum += revenus[i]
    return sum / len(revenus)

In [8]:
moy(revenus)

2134.4

3-

In [9]:
import numpy
revenus = numpy.array(revenus)

4-

In [10]:
numpy.mean(revenus)

2134.4

5-

In [11]:
numpy.argmin(revenus)

1

In [12]:
numpy.argmax(revenus)

3

6-

In [13]:
revenus.sort()

7-

In [14]:
revenus[:3]

array([1500, 1800, 2172])

8-

In [15]:
revenus[::2]

array([1500, 2172, 3000])

9-

In [16]:
revenus[revenus > 2000]

array([2172, 2200, 3000])

10-

In [17]:
m = numpy.random.randint(1, 11, size=(10, 10))
m

array([[ 6,  1,  2,  1,  7,  2,  1, 10,  1,  6],
       [ 2,  8,  9,  7,  8,  7,  6, 10,  1,  7],
       [ 2,  9,  8,  7, 10,  9,  6, 10,  3,  2],
       [ 2,  2,  1,  2,  7,  4,  8, 10,  8,  7],
       [ 9,  2,  8,  7,  6,  7,  2,  9,  8,  1],
       [ 3,  8,  6,  8,  4,  8,  7,  5, 10,  5],
       [ 3, 10,  9,  4,  9,  1,  7,  6,  9, 10],
       [10,  2,  3,  5,  8, 10,  7,  7,  2,  5],
       [ 4,  6,  1,  4,  9,  8,  6,  8,  3,  1],
       [10, 10,  6,  1,  4, 10,  8,  9,  1,  5]])

11-

In [18]:
m[0]

array([ 6,  1,  2,  1,  7,  2,  1, 10,  1,  6])

12-

In [19]:
m = numpy.vstack((m, numpy.random.randint(1, 11, size=(1, 10))))
m

array([[ 6,  1,  2,  1,  7,  2,  1, 10,  1,  6],
       [ 2,  8,  9,  7,  8,  7,  6, 10,  1,  7],
       [ 2,  9,  8,  7, 10,  9,  6, 10,  3,  2],
       [ 2,  2,  1,  2,  7,  4,  8, 10,  8,  7],
       [ 9,  2,  8,  7,  6,  7,  2,  9,  8,  1],
       [ 3,  8,  6,  8,  4,  8,  7,  5, 10,  5],
       [ 3, 10,  9,  4,  9,  1,  7,  6,  9, 10],
       [10,  2,  3,  5,  8, 10,  7,  7,  2,  5],
       [ 4,  6,  1,  4,  9,  8,  6,  8,  3,  1],
       [10, 10,  6,  1,  4, 10,  8,  9,  1,  5],
       [ 3, 10, 10,  4,  8,  7,  4,  9,  7,  1]])

13-

In [20]:
m = m[:-1]
m

array([[ 6,  1,  2,  1,  7,  2,  1, 10,  1,  6],
       [ 2,  8,  9,  7,  8,  7,  6, 10,  1,  7],
       [ 2,  9,  8,  7, 10,  9,  6, 10,  3,  2],
       [ 2,  2,  1,  2,  7,  4,  8, 10,  8,  7],
       [ 9,  2,  8,  7,  6,  7,  2,  9,  8,  1],
       [ 3,  8,  6,  8,  4,  8,  7,  5, 10,  5],
       [ 3, 10,  9,  4,  9,  1,  7,  6,  9, 10],
       [10,  2,  3,  5,  8, 10,  7,  7,  2,  5],
       [ 4,  6,  1,  4,  9,  8,  6,  8,  3,  1],
       [10, 10,  6,  1,  4, 10,  8,  9,  1,  5]])

### Partie 3 - La bibliothèque Pandas
1-

In [21]:
import pandas

tab1 = {
    "state": ["Tunis", "Bizerte", "Sfax", "Sousse", "Gabes"],
    "year": [2000, 2001, 2002, 2001, 2002],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9]
}

df1 = pandas.DataFrame(tab1)

2-

In [22]:
pandas.DataFrame.info(df1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   state   5 non-null      object 
 1   year    5 non-null      int64  
 2   pop     5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes


3-

In [23]:
df1

state  year  pop
0    Tunis  2000  1.5
1  Bizerte  2001  1.7
2     Sfax  2002  3.6
3   Sousse  2001  2.4
4    Gabes  2002  2.9

4-

In [24]:
df1.columns

Index(['state', 'year', 'pop'], dtype='object')

5-

In [25]:
df1["year"]

0    2000
1    2001
2    2002
3    2001
4    2002
Name: year, dtype: int64

6-

In [26]:
df1["pop"] = 5.5
df1

state  year  pop
0    Tunis  2000  5.5
1  Bizerte  2001  5.5
2     Sfax  2002  5.5
3   Sousse  2001  5.5
4    Gabes  2002  5.5

7-

In [27]:
df1["zone"] = ""
df1

state  year  pop zone
0    Tunis  2000  5.5     
1  Bizerte  2001  5.5     
2     Sfax  2002  5.5     
3   Sousse  2001  5.5     
4    Gabes  2002  5.5

8-

In [28]:
df1 = df1.rename(columns={"state": "A", "year": "B", "pop": "C", "zone": "D"})

In [29]:
df1

A     B    C D
0    Tunis  2000  5.5  
1  Bizerte  2001  5.5  
2     Sfax  2002  5.5  
3   Sousse  2001  5.5  
4    Gabes  2002  5.5

9-

In [30]:
del df1["A"]

In [31]:
df1

B    C D
0  2000  5.5  
1  2001  5.5  
2  2002  5.5  
3  2001  5.5  
4  2002  5.5

### Partie 4: Exploration des données