### Partie 1 - Rappel python
1- 

In [1]:
a = float(input("a: "))
b = float(input("b: "))
c = float(input("c: "))

In [2]:
import math
d = pow(b, 2) - 4 * a * c

In [3]:
if d > 0:
    root1 = (-b + math.sqrt(d)) / (2*a)
    root2 = (-b - math.sqrt(d)) / (2*a)
    print(f"The roots are: {root1} and {root2}")
    print(f"result 1= {a * pow(root1, 2) + b * root1 + c}")
    print(f"result 2= {a * pow(root2, 2) + b * root2 + c}")
elif d == 0:
    root = -b / (2*a)
    print(f"The root is: {root}")
    print(f"result 2= {a * pow(root, 2) + b * root + c}")
else:
    real_part = -b / (2*a)
    imaginary_part = math.sqrt(-d) / (2*a)
    root1 = complex(real_part, imaginary_part)
    root2 = complex(real_part, -imaginary_part)
    print(f"The roots are complex: {root1} and {root2}")
    print(f"result 1= {a * pow(root1, 2) + b * root1 + c}")
    print(f"result 2= {a * pow(root2, 2) + b * root2 + c}")

The roots are complex: (-0.3333333333333333+0.47140452079103173j) and (-0.3333333333333333-0.47140452079103173j)
result 1= 0j
result 2= 0j


2-

In [4]:
def nombreOcurrences(caractere, mot):
    count = 0
    for c in mot:
        if c == caractere:
            count += 1
    return count

In [5]:
nombreOcurrences('a', 'java')

2

### Partie 2 - La bibliothèque numpy
1-

In [6]:
revenus = [1800, 1500, 2200, 3000, 2172]

2-

In [7]:
def moy(revenus):
    sum = 0
    for i in range(len(revenus)):
        sum += revenus[i]
    return sum / len(revenus)

In [8]:
moy(revenus)

2134.4

3-

In [9]:
import numpy
revenus = numpy.array(revenus)

4-

In [10]:
numpy.mean(revenus)

2134.4

5-

In [11]:
numpy.argmin(revenus)

1

In [12]:
numpy.argmax(revenus)

3

6-

In [13]:
revenus.sort()

7-

In [14]:
revenus[:3]

array([1500, 1800, 2172])

8-

In [15]:
revenus[::2]

array([1500, 2172, 3000])

9-

In [16]:
revenus[revenus > 2000]

array([2172, 2200, 3000])

10-

In [17]:
m = numpy.random.randint(1, 11, size=(10, 10))
m

array([[ 6,  1,  2,  1,  7,  2,  1, 10,  1,  6],
       [ 2,  8,  9,  7,  8,  7,  6, 10,  1,  7],
       [ 2,  9,  8,  7, 10,  9,  6, 10,  3,  2],
       [ 2,  2,  1,  2,  7,  4,  8, 10,  8,  7],
       [ 9,  2,  8,  7,  6,  7,  2,  9,  8,  1],
       [ 3,  8,  6,  8,  4,  8,  7,  5, 10,  5],
       [ 3, 10,  9,  4,  9,  1,  7,  6,  9, 10],
       [10,  2,  3,  5,  8, 10,  7,  7,  2,  5],
       [ 4,  6,  1,  4,  9,  8,  6,  8,  3,  1],
       [10, 10,  6,  1,  4, 10,  8,  9,  1,  5]])

11-

In [18]:
m[0]

array([ 6,  1,  2,  1,  7,  2,  1, 10,  1,  6])

12-

In [19]:
m = numpy.vstack((m, numpy.random.randint(1, 11, size=(1, 10))))
m

array([[ 6,  1,  2,  1,  7,  2,  1, 10,  1,  6],
       [ 2,  8,  9,  7,  8,  7,  6, 10,  1,  7],
       [ 2,  9,  8,  7, 10,  9,  6, 10,  3,  2],
       [ 2,  2,  1,  2,  7,  4,  8, 10,  8,  7],
       [ 9,  2,  8,  7,  6,  7,  2,  9,  8,  1],
       [ 3,  8,  6,  8,  4,  8,  7,  5, 10,  5],
       [ 3, 10,  9,  4,  9,  1,  7,  6,  9, 10],
       [10,  2,  3,  5,  8, 10,  7,  7,  2,  5],
       [ 4,  6,  1,  4,  9,  8,  6,  8,  3,  1],
       [10, 10,  6,  1,  4, 10,  8,  9,  1,  5],
       [ 3, 10, 10,  4,  8,  7,  4,  9,  7,  1]])

13-

In [20]:
m = m[:-1]
m

array([[ 6,  1,  2,  1,  7,  2,  1, 10,  1,  6],
       [ 2,  8,  9,  7,  8,  7,  6, 10,  1,  7],
       [ 2,  9,  8,  7, 10,  9,  6, 10,  3,  2],
       [ 2,  2,  1,  2,  7,  4,  8, 10,  8,  7],
       [ 9,  2,  8,  7,  6,  7,  2,  9,  8,  1],
       [ 3,  8,  6,  8,  4,  8,  7,  5, 10,  5],
       [ 3, 10,  9,  4,  9,  1,  7,  6,  9, 10],
       [10,  2,  3,  5,  8, 10,  7,  7,  2,  5],
       [ 4,  6,  1,  4,  9,  8,  6,  8,  3,  1],
       [10, 10,  6,  1,  4, 10,  8,  9,  1,  5]])

### Partie 3 - La bibliothèque Pandas
1-

In [21]:
import pandas

tab1 = {
    "state": ["Tunis", "Bizerte", "Sfax", "Sousse", "Gabes"],
    "year": [2000, 2001, 2002, 2001, 2002],
    "pop": [1.5, 1.7, 3.6, 2.4, 2.9]
}

df1 = pandas.DataFrame(tab1)

2-

In [22]:
pandas.DataFrame.info(df1)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   state   5 non-null      object 
 1   year    5 non-null      int64  
 2   pop     5 non-null      float64
dtypes: float64(1), int64(1), object(1)
memory usage: 252.0+ bytes


3-

In [23]:
df1

state  year  pop
0    Tunis  2000  1.5
1  Bizerte  2001  1.7
2     Sfax  2002  3.6
3   Sousse  2001  2.4
4    Gabes  2002  2.9

4-

In [24]:
df1.columns

Index(['state', 'year', 'pop'], dtype='object')

5-

In [25]:
df1["year"]

0    2000
1    2001
2    2002
3    2001
4    2002
Name: year, dtype: int64

6-

In [26]:
df1["pop"] = 5.5
df1

state  year  pop
0    Tunis  2000  5.5
1  Bizerte  2001  5.5
2     Sfax  2002  5.5
3   Sousse  2001  5.5
4    Gabes  2002  5.5

7-

In [27]:
df1["zone"] = ""
df1

state  year  pop zone
0    Tunis  2000  5.5     
1  Bizerte  2001  5.5     
2     Sfax  2002  5.5     
3   Sousse  2001  5.5     
4    Gabes  2002  5.5

8-

In [28]:
df1 = df1.rename(columns={"state": "A", "year": "B", "pop": "C", "zone": "D"})

In [29]:
df1

A     B    C D
0    Tunis  2000  5.5  
1  Bizerte  2001  5.5  
2     Sfax  2002  5.5  
3   Sousse  2001  5.5  
4    Gabes  2002  5.5

9-

In [30]:
del df1["A"]

In [31]:
df1

B    C D
0  2000  5.5  
1  2001  5.5  
2  2002  5.5  
3  2001  5.5  
4  2002  5.5

### Partie 4: Exploration des données

In [1]:
import matplotlib as mp
import matplotlib.pyplot as plt
import seaborn as sb

1

In [7]:
import pandas
path = "pima-indians-diabetes.data.csv"
df = pandas.read_csv(path)

2

In [8]:
df.columns = ["NumTimesPrg", "PlGlcConc", "BloodP", "SkinThick", "TwoHourSerIns", "BMI", "DiPedFunc", "age", "HasDiabetes"]

3

In [9]:
df.head()

NumTimesPrg  PlGlcConc  BloodP  SkinThick  TwoHourSerIns   BMI  DiPedFunc  \
0            1         85      66         29              0  26.6      0.351   
1            8        183      64          0              0  23.3      0.672   
2            1         89      66         23             94  28.1      0.167   
3            0        137      40         35            168  43.1      2.288   
4            5        116      74          0              0  25.6      0.201   

   age  HasDiabetes  
0   31            0  
1   32            1  
2   21            0  
3   33            1  
4   30            0

4

In [10]:
df["BloodP"]

0      66
1      64
2      66
3      40
4      74
       ..
762    76
763    70
764    72
765    60
766    70
Name: BloodP, Length: 767, dtype: int64

5

In [11]:
df.info

<bound method DataFrame.info of      NumTimesPrg  PlGlcConc  BloodP  SkinThick  TwoHourSerIns   BMI  \
0              1         85      66         29              0  26.6   
1              8        183      64          0              0  23.3   
2              1         89      66         23             94  28.1   
3              0        137      40         35            168  43.1   
4              5        116      74          0              0  25.6   
..           ...        ...     ...        ...            ...   ...   
762           10        101      76         48            180  32.9   
763            2        122      70         27              0  36.8   
764            5        121      72         23            112  26.2   
765            1        126      60          0              0  30.1   
766            1         93      70         31              0  30.4   

     DiPedFunc  age  HasDiabetes  
0        0.351   31            0  
1        0.672   32            1  
2        0

In [18]:
df[["age","HasDiabetes"]].describe()

age  HasDiabetes
count  767.000000   767.000000
mean    33.219035     0.348110
std     11.752296     0.476682
min     21.000000     0.000000
25%     24.000000     0.000000
50%     29.000000     0.000000
75%     41.000000     1.000000
max     81.000000     1.000000

In [15]:
df.corr()

NumTimesPrg  PlGlcConc    BloodP  SkinThick  TwoHourSerIns  \
NumTimesPrg       1.000000   0.128846  0.141197  -0.082495      -0.072999   
PlGlcConc         0.128846   1.000000  0.152498   0.056381       0.332383   
BloodP            0.141197   0.152498  1.000000   0.207308       0.089098   
SkinThick        -0.082495   0.056381  0.207308   1.000000       0.437974   
TwoHourSerIns    -0.072999   0.332383  0.089098   0.437974       1.000000   
BMI               0.017518   0.220955  0.281777   0.392553       0.198111   
DiPedFunc        -0.033927   0.136903  0.041180   0.183498       0.185579   
age               0.544018   0.262408  0.239571  -0.115873      -0.040942   
HasDiabetes       0.221087   0.465856  0.064882   0.073265       0.131984   

                    BMI  DiPedFunc       age  HasDiabetes  
NumTimesPrg    0.017518  -0.033927  0.544018     0.221087  
PlGlcConc      0.220955   0.136903  0.262408     0.465856  
BloodP         0.281777   0.041180  0.239571     0.064882  
SkinThick      0.392553   0.183498 -0.115873     0.073265  
TwoHourSerIns  0.198111   0.185579 -0.040942     0.131984  
BMI            1.000000   0.140546  0.035911     0.292695  
DiPedFunc      0.140546   1.000000  0.032738     0.173245  
age            0.035911   0.032738  1.000000     0.236417  
HasDiabetes    0.292695   0.173245  0.236417     1.000000

In [16]:
df['HasDiabetes'].value_counts()

HasDiabetes
0    500
1    267
Name: count, dtype: int64

In [21]:
df[["age","HasDiabetes"]].values

array([[31,  0],
       [32,  1],
       [21,  0],
       ...,
       [30,  0],
       [47,  1],
       [23,  0]], dtype=int64)